Controllers/SquadController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyTeam.Areas.Identity.Data;
using MyTeam.Models;

namespace MyTeam.Controllers
{
    public class SquadController : MyTeamController
    {
        public SquadController(UserManager<MyTeamUser> userManager) : base(userManager)
        {
        }
        public async Task<IActionResult> Index()
        {
            var myTeamEnumName = GetMyCurrentEnumTeamName();
            var myTeamId = Convert.ToInt32(myTeamEnumName);
            var uri = "v2/teams/" + myTeamId;
            var myTeam = await GetFootballDataResources(new Team(),uri);
            return View(myTeam);
        }

      
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Team</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/DataTables-1.10.20/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="~/lib/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/lib/OwlCarousel2-2.3.4/dist/assets/owl.theme.default.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
     <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/DataTables-1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/DataTables-1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/OwlCarousel2-2.3.4/dist/owl.carousel.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="OverView" asp-action="Index">My Team</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="OverView" asp-action="Index">Overview</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Squad" asp-action="Index">Squad</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Matches" asp-action="Index">Scheduled Matches</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - footyline
        </div>
    </footer>    
   
</body>
</html>