ViewModels/SelectedTeamViewModel.cs
using System.Collections.Generic;
using MyTeam.Models;

namespace MyTeam.ViewModels
{
    public class SelectedTeamViewModel
    {
        public Team Team { get; set; }
        public TeamMatches TeamMatches { get; set; }
    }

    public class TeamMatches
    {
        public List<Match> Matches { get; set; }
    }
}

Controllers/OverViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using MyTeam.Models;
using Microsoft.AspNetCore.Mvc;
using MyTeam.Areas.Identity.Data;
using MyTeam.ViewModels;
using Newtonsoft.Json;

namespace MyTeam.Controllers
{
    public class OverViewController : MyTeamController
    {
        public OverViewController(UserManager<MyTeamUser> userManager) : base(userManager)
        {
        }
        public async Task<IActionResult> Index()
        {
            var myTeamEnumName = GetMyCurrentEnumTeamName();
            var myTeamId = Convert.ToInt32(myTeamEnumName);
            var teamUri = "v2/teams/" + myTeamId;
            var viewModel = new OverViewModel();
            viewModel.MyTeam = await GetFootballDataResources(new Team(), teamUri);
            var competitionIds = viewModel.MyTeam.ActiveCompetitions
                .Where(a =>a.Plan == "TIER_ONE")
                .Select(a => a.Id).ToList();
            var i = 0;
            foreach (var uri in competitionIds.Select(competitionId => "v2/competitions/" + competitionId + "/standings"))
            {
                viewModel.CompetitionStandings.Add(await GetFootballDataResources(new CompetitionStandings(), uri));
                var filteredStandings = viewModel.CompetitionStandings[i].Standings.Where(s => s.Type == "TOTAL").ToList();
                viewModel.CompetitionStandings[i].Standings = filteredStandings;
                i++;
            }

            viewModel.News = await GetMyTeamNews(myTeamEnumName.ToString().ToLower());
            
            return View(viewModel);
        }

        public async Task<IActionResult> TopScorer()
        {
            var viewModel = new ScorerViewModel();
            var myTeamEnumName = GetMyCurrentEnumTeamName();
            var myTeamId = Convert.ToInt32(myTeamEnumName);
            var teamUri = "v2/teams/" + myTeamId;
            var myTeam = await GetFootballDataResources(new Team(), teamUri);
            var competitionIds = myTeam.ActiveCompetitions
                .Where(a =>a.Plan == "TIER_ONE")
                .Select(a => a.Id).ToList();
            
            foreach (var competitionId in competitionIds)
            {
                var uri = "v2/competitions/" + competitionId + "/scorers";
                viewModel.ScorerStandings.Add(await GetFootballDataResources(new ScorerStandings(), uri));
            }
            return View(viewModel);
        }
        
        public async Task<IActionResult> SelectedTeam(int id)
        {
            var dateFrom = DateTime.Now.AddMonths(-1).ToString("yyyy-MM-dd");
            var dateTo = DateTime.Now.ToString("yyyy-MM-dd");
            var matchesUri = "v2/teams/" + id + "/matches?dateFrom=" + dateFrom + "&dateTo=" + dateTo;
            var teamUri = "v2/teams/" + id;
            var viewModel = new SelectedTeamViewModel
            {
                Team = await GetFootballDataResources(new Team(), teamUri),
                TeamMatches = await GetFootballDataResources(new TeamMatches(), matchesUri)
            };
            return View(viewModel);
        }
        
        private static HttpClient EstablishSkySportApiConnection()
        {
            var client = new HttpClient();
            const string baseUrl = "https://skysportsapi.herokuapp.com/";
            client.BaseAddress = new Uri(baseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            return client;
        }
        private static async Task<List<News>> GetMyTeamNews(string myTeamName)
        {
            var client = EstablishSkySportApiConnection();
            var res = await client.GetAsync("sky/football/getteamnews/" + myTeamName + "/v1.0");
            var myTeamNews = new List<News>();
            if (res.IsSuccessStatusCode)
            {
                var teamResponse = res.Content.ReadAsStringAsync().Result;
                myTeamNews = JsonConvert.DeserializeObject<List<News>>(teamResponse);
            }
            return myTeamNews;
        }
    }
}

Views/OverView/Index.cshtml
@model MyTeam.ViewModels.OverViewModel
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div>
    <a style="color: goldenrod"><img src="@Model.MyTeam.CrestUrl" alt="" style="width: 35px;height: 35px"/> Welcome To @Model.MyTeam.Name's Overview</a>
</div>
<br/>
<h3 style="color: darkgoldenrod">News</h3>
<div class="owl-carousel">
    @foreach (var news in Model.News)
    {
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="@news.ImgSrc" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@news.Title</h5>
                <a href="@news.Link" class="btn btn-primary">Read More</a>
                  <p class="card-text"><small class="text-muted">Sky Sport</small></p>
            </div>
        </div>
    }
   
</div>

<h3 style="color: darkgoldenrod">Standings</h3>
@foreach (var competitionStanding in Model.CompetitionStandings)
{
    <h5>@competitionStanding.Competition.Name</h5>
    <table class="display table table-striped table-bordered table-hover" style="width:100%">
        <thead>
        <tr>
            <th></th>
            <th>Team</th>
            <th>Pts</th>
            <th>P</th>
            <th>W</th>
            <th>D</th>
            <th>L</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var tableItem in competitionStanding.Standings.First(s => s.Table.Any(t => t.Team.Id == Model.MyTeam.Id)).Table)
        {
            <tr>
                <td>@tableItem.Position</td>
                <td>
                    <img src="@tableItem.Team.CrestUrl" alt="" style="width: 30px;height: 30px"/>
                    @Html.ActionLink(tableItem.Team.Name, "SelectedTeam", new {id = tableItem.Team.Id}, new {style = "color:#000000"})
                </td>
                <td>@tableItem.Points</td>
                <td>@tableItem.PlayedGames</td>
                <td>@tableItem.Won</td>
                <td>@tableItem.Draw</td>
                <td>@tableItem.Lost</td>
            </tr>
        }
        </tbody>
    </table>
}
<br/>
<a href="@Url.Action("TopScorer", "OverView")" class="btn btn-primary">Competitions Top Scores</a>

@section Scripts
{
    <script>
        $(document).ready(function() {
             $('table.display').DataTable({
                "searching": false,
                "info": false,
                "paging" : false
             });
              $(".owl-carousel").owlCarousel();
         });
    </script>
}

Views/OverView/SelectedTeam.cshtml
@model MyTeam.ViewModels.SelectedTeamViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h3 style="color: darkgoldenrod"><img src="@Model.Team.CrestUrl" alt="" style="width: 30px;height: 30px"/> @Model.Team.Name's Latest Matches</h3>
 <table class="table" style="width:100%">
     <tbody>
            @foreach (var match in Model.TeamMatches.Matches)
            {
                <tr>
                    <td>
                        <h3>
                            <span class="badge badge-pill 
                                @(match.Score.FullTime.HomeTeam > match.Score.FullTime.AwayTeam ? "badge-success" 
                                        : match.Score.FullTime.HomeTeam < match.Score.FullTime.AwayTeam ? "badge-danger" 
                                                : "badge-dark")">@match.Score.FullTime.HomeTeam
                            </span>
                        </h3>
                    </td>
                    <td>
                        <h3><span class="badge badge-pill badge-light">@match.HomeTeam.Name</span></h3>
                    </td>
                    <td>
                        <h3><span class="badge badge-pill badge-primary">VS</span></h3>
                    </td>
                    <td>
                          <h3><span class="badge badge-pill badge-light">@match.AwayTeam.Name</span></h3>
                    </td>
                    <td>
                        <h3>
                            <span class="badge badge-pill 
                                @(match.Score.FullTime.AwayTeam > match.Score.FullTime.HomeTeam ? "badge-success" 
                                    : match.Score.FullTime.AwayTeam < match.Score.FullTime.HomeTeam ? "badge-danger" 
                                        : "badge-dark")">@match.Score.FullTime.AwayTeam
                            </span>
                        </h3>
                    </td>
                </tr>
            }
        </tbody>
 </table>

<h3 style="color: darkgoldenrod"><img src="@Model.Team.CrestUrl" alt="" style="width: 30px;height: 30px"/> @Model.Team.Name's Squad</h3>
<table id="ItemsTable" class="table table-striped" style="width:100%">
    <thead>
    <tr>
        <th>Name</th>
        <th>Position</th>
        <th>Nationality</th>
        <th>Birth Date</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var player in Model.Team.Squad)
    {
        <tr>
            <td>@player.Name</td>
            <td>@player.Position</td>
            <td>@player.Nationality</td>
            <td>@player.DateOfBirth.ToString("yyyy MM dd dddd")</td>
        </tr>
    }
    </tbody>
</table>

@section Scripts
{
    <script>
        $(document).ready(function() {
             $('#ItemsTable').DataTable({
                "searching": false,
                "info": false
             });
         });
    </script>
}

Views/OverView/TopScorer.cshtml
@model MyTeam.ViewModels.ScorerViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h3 style="color: darkgoldenrod">Competitions Top Scores</h3>
@foreach (var scorerStanding in Model.ScorerStandings)
{
    <h5>@scorerStanding.Competition.Name</h5>
    <table class="display table table-striped table-bordered table-hover" style="width:60%">
        <thead>
        <tr>
            <th>Name</th>
            <th>Team</th>
            <th>Goals</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var tableItem in scorerStanding.Scorers)
        {
            <tr>
                <td>@tableItem.Player.Name</td>
                <td>@tableItem.Team.Name</td>
                <td>@tableItem.NumberOfGoals</td>
            </tr>
        }
        </tbody>
    </table>
}